#!/usr/bin/env bash
# /redirect_me redirects to different page

apt-get -y update
apt-get -y upgrade
apt-get -y install nginx
sed -i "21s/^listen .*/listen 80" /etc/nginx/sites-enabled/default
ufw allow 'Nginx HTTP'
echo "Hello World!" >> /var/www/html/index.html
file_path=/etc/nginx/sites-enabled/default
redirect="\rewrite ^/redirect_me https://www.youtube.com/watch?v=QH2-TGUlwu4/$1";
sed -i " /server_name _;/a ${redirect} permanent;" $file_path
service nginx restart